// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(MarryUsContext))]
    partial class MarryUsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CategoryStatus")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Entities.Concrete.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CommentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CommentStatus")
                        .HasColumnType("bit");

                    b.Property<string>("CommentTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeddingPlaceId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.Concrete.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrganizationDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("Price")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WeddingPlaceId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("WeddingPlaceId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entities.Concrete.PlaceType", b =>
                {
                    b.Property<int>("PlaceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PlaceTypeName")
                        .HasColumnType("int");

                    b.HasKey("PlaceTypeId");

                    b.ToTable("PlaceType");
                });

            modelBuilder.Entity("Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("IsWeddingPlaceOwner")
                        .HasColumnType("bit");

                    b.Property<string>("Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Entities.Concrete.WeddingPlace", b =>
                {
                    b.Property<int>("WeddingPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<short>("Capacity")
                        .HasColumnType("smallint");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Discount_1")
                        .HasColumnType("smallint");

                    b.Property<short>("Discount_2")
                        .HasColumnType("smallint");

                    b.Property<short>("Discount_3")
                        .HasColumnType("smallint");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceOwnerId")
                        .HasColumnType("int");

                    b.Property<int>("PlacePhotoId")
                        .HasColumnType("int");

                    b.Property<bool>("PlaceStatus")
                        .HasColumnType("bit");

                    b.Property<int>("PlaceTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PlateCode")
                        .HasColumnType("int");

                    b.Property<string>("PlateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PriceFirst")
                        .HasColumnType("float");

                    b.Property<double>("PriceLast")
                        .HasColumnType("float");

                    b.Property<int?>("WeddingPlaceImagePlacePhotoId")
                        .HasColumnType("int");

                    b.Property<bool>("isAlcoholIncluded")
                        .HasColumnType("bit");

                    b.Property<bool>("isFoodIncluded")
                        .HasColumnType("bit");

                    b.Property<bool>("isReserved")
                        .HasColumnType("bit");

                    b.HasKey("WeddingPlaceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlaceTypeId");

                    b.HasIndex("WeddingPlaceImagePlacePhotoId");

                    b.ToTable("WeddingPlaces");
                });

            modelBuilder.Entity("Entities.Concrete.WeddingPlaceImage", b =>
                {
                    b.Property<int>("PlacePhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlacePhotoId");

                    b.ToTable("WeddingPlaceImage");
                });

            modelBuilder.Entity("Entities.Concrete.Order", b =>
                {
                    b.HasOne("Entities.Concrete.WeddingPlace", "WeddingPlace")
                        .WithMany()
                        .HasForeignKey("WeddingPlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeddingPlace");
                });

            modelBuilder.Entity("Entities.Concrete.WeddingPlace", b =>
                {
                    b.HasOne("Entities.Concrete.Category", "Category")
                        .WithMany("WeddingPlaces")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.PlaceType", "PlaceType")
                        .WithMany("WeddingPlaces")
                        .HasForeignKey("PlaceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.WeddingPlaceImage", "WeddingPlaceImage")
                        .WithMany()
                        .HasForeignKey("WeddingPlaceImagePlacePhotoId");

                    b.Navigation("Category");

                    b.Navigation("PlaceType");

                    b.Navigation("WeddingPlaceImage");
                });

            modelBuilder.Entity("Entities.Concrete.Category", b =>
                {
                    b.Navigation("WeddingPlaces");
                });

            modelBuilder.Entity("Entities.Concrete.PlaceType", b =>
                {
                    b.Navigation("WeddingPlaces");
                });
#pragma warning restore 612, 618
        }
    }
}
